apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webdev-role
  namespace: web
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webdev-role-rb
  namespace: web
subjects:
- kind: Group
  name: webdev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: webdev-role
  apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: webadmins-role
# rules:
# - apiGroups: ["*"] 
#   resources: ["*"]
#   verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webadmins-role-web-rb
  namespace: web
subjects:
- kind: Group
  name: webadmins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webadmins-role-db-rb
  namespace: databases
subjects:
- kind: Group
  name: webadmins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io